services:
  mysql:
    image: mysql:8.0
    container_name: gamerneeds-mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - gamerneeds-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: gamerneeds-backend
    env_file: .env
    environment:
      - DB_HOST=host.docker.internal
      - NODE_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gamerneeds-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: gamerneeds-frontend
    env_file: .env
    environment:
      - VITE_API_URL=http://107.22.32.241:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - gamerneeds-network

networks:
  gamerneeds-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local