services:
  mysql:
    image: mysql:8.0
    container_name: gamerneeds-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - gamerneeds-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: gamerneeds-backend
    env_file: ./Backend/.env
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - NODE_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - gamerneeds-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: gamerneeds-frontend
    env_file: ./Frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - gamerneeds-network
    restart: unless-stopped

networks:
  gamerneeds-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local