services:
  mysql:
    image: mysql:8.0
    container_name: gamerneeds-mysql
    env_file: ./Backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - gamerneeds-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: gamerneeds-backend
    env_file: ./Backend/.env
    environment:
      - DB_HOST=mysql
      - NODE_ENV=development
      - DEBUG=express:*
    command: ["npm", "run", "debug"]
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app  # Añadido para desarrollo
      - /app/node_modules  # Añadido para preservar node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gamerneeds-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: gamerneeds-frontend
    env_file: ./Frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - gamerneeds-network

networks:
  gamerneeds-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local